// <auto-generated />
namespace EZPZPOS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DataLayerMigrationWithApplicationUserBuiltOutMore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataLayerMigrationWithApplicationUserBuiltOutMore));
        
        string IMigrationMetadata.Id
        {
            get { return "202009281911531_DataLayerMigrationWithApplicationUserBuiltOutMore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
